version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"
    assignees:
      - "simonwalz"
    versioning-strategy: "auto"
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/webui"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"
  - package-ecosystem: "docker"
    directory: "/dev-container"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"
  - package-ecosystem: "npm"
    directory: "/webui"
    schedule:
      interval: "daily"
    assignees:
      - "simonwalz"