#!/bin/bash

SOCKET_PATH="/var/run/cuos.sock"

cuos_api() {
  local command="$1"
  local json_data="${2:-""}"
  if [[ ! -S $SOCKET_PATH ]]; then
    echo "Socket does not exist: $SOCKET_PATH" >&2
    return 2
  fi
  if [[ "${json_data}" == "-" ]]; then
    json_data="$(cat)"
  fi

  # open file descritor for socat. Input from pipe, Output to stdout
  exec 3> >(socat - UNIX-CONNECT:$SOCKET_PATH)
  local socat_pid="$!"

  # Send a command
  echo "${json_data:-"{}"}" | jq -c --arg command "$command" '.command = $command' >&3
  # wait that socat exists
  wait -f "${socat_pid}"
  # close file descriptor and get return value of socat
  local return_code="$?"
  if [[ "${return_code}" != "0" ]]; then
    echo "socat exited with return code ${return_code}." >&2
    return 1
  fi

  exec 3>&-

  return 0
}


COMMAND="${1:-}"
INPUT="{}"
if [[ -z "${COMMAND}" ]]; then
  read -r INPUT
  COMMAND="$(jq -r '.app_command // empty' <<< "${INPUT}")"
elif [[ "${2:-}" == "-" ]]; then
  read -r INPUT
fi

if [[ "${COMMAND}" = "" || "${COMMAND}" = "help" || "${COMMAND}" = "--help" ]]; then
  cat <<EOF
USAGE: cuos-iac ACTION

ACTIONS:
EOF

  grep -E "^##" "${BASH_SOURCE[0]}" | sed -e 's/^## \?//'

  echo

## update             - Trigger update of the IaC definitions
elif [[ "${COMMAND}" = "update" ]]; then
	killall sleep

## ps                 - Show docker ps as JSON
elif [[ "${COMMAND}" = "ps" ]]; then
	docker ps -a --format '{{json .}}' | jq -s .
	#COMPOSE_PROJECT_NAME="iac" docker-compose -f /volume/repo/docker-compose.yml ps --format '{{json .}}'

## state              - Provide IaC state
elif [[ "${COMMAND}" = "state" ]]; then
	cat /volume/state.json

elif [[ "${COMMAND}" == "cuos:version" || \
    "${COMMAND}" == "cuos:version:json" || \
    "${COMMAND}" == "cuos:log" || \
    "${COMMAND}" == "cuos:state" || \
    "${COMMAND}" == "cuos:resources" || \
    "${COMMAND}" == "cuos:shutdown" || \
    "${COMMAND}" == "cuos:reboot" || \
    "${COMMAND}" == "cuos:rollback" ]]; then
  if [[ ! -S $SOCKET_PATH ]]; then
    exit 0
  fi

  COMMAND="${COMMAND//cuos:/}"
  cuos_api "${COMMAND}"

elif [[ "${COMMAND}" = "config" ]]; then
  set -x

  SIGNING_KEYS_FILE="${T_SIGNING_KEYS_FILE:-"/volume/signing_keys"}"
  compact="$(echo "${INPUT}" | jq -r '.config // empty')"
  ns="file"

  # helpers
  b64url_to_b64(){
    s="$(cat)"
    mod=$(( ${#s} % 4 ))
    if [ $mod -eq 2 ]; then s="${s}=="
    elif [ $mod -eq 3 ]; then s="${s}="
    elif [ $mod -ne 0 ]; then return 1; fi
    printf '%s' "$s" | tr -- '-_' '+/'
  }

  # split into payload, sig
  payload_b64url="${compact%%.*}"
  sig_b64url="${compact#*.}"

  [ -n "$payload_b64url" ] && [ -n "$sig_b64url" ] || { echo "invalid compact input"; exit 2; }

  # decode payload to json (kept in variable)
  json="$(printf '%s' "$payload_b64url" | b64url_to_b64 | base64 -d)" || { echo "invalid payload"; exit 3; }

  if ! principal="$(ssh-keygen -Y find-principals -f "${SIGNING_KEYS_FILE}" \
      -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d))"; then
    echo "no principal identified."
    exit 4
  fi


  if ! printf '%s' "$json" | ssh-keygen -Y verify \
      -f "${SIGNING_KEYS_FILE}" \
      -n "$ns" \
      -I "$principal" \
      -s <(printf '%s' "$sig_b64url" | b64url_to_b64 | base64 -d); then
    echo "Can not validate."
    exit 5
  fi

  now="$(date +%s)"
  iat="$(printf '%s' "$json" | jq -r '.iat // empty')"
  iat="${iat%%.*}"
  if ! [[ "${iat}" =~ ^[0-9]+$ ]]; then
    echo "invalid or missing iat: $iat"
    exit 6
  fi

  # Signature is only valid for 15mins:
  if (( now > iat - 60 )) && (( now < iat + 900 )); then
    name=$(echo "${json}" | jq -r '.name // "unknown"')
    echo "Config signed by ${name}"
    echo "Passing config to system ..."

    echo "${json}" | jq '{"config": .config}' | cuos_api "update" "-"
    exit 0
  fi

  echo "Error: iat outside allowed window" >&2
  echo "${now} - ${iat} = $(( now - iat ))"
  exit 7

else
  echo "No valid command provided. Exiting."

fi
